spring.application.name=risk-predictor-service
server.port=8080
ai.model.api.base-url=http://localhost:5000
spring.main.allow-bean-definition-overriding=true
spring.data.mongodb.uri=mongodb+srv://haribabutatikonda3:kbQ6WiXghST76iEj@personaldb.lsqarap.mongodb.net/healthdb?retryWrites=true&w=majority&appName=PersonalDB